version: '3'

services:
  grafana:
    #image: grafana/grafana:latest
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource


volumes:
  grafana-data:
    driver: local

