version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - 5601:5601
    environment:
      # ELASTICSEARCH_HOSTS: '["http://localhost:9200","http://34.102.87.141:9200", "http://10.0.100.140:9200"]'
      # ELASTICSEARCH_HOSTS: '["http://10.0.100.140:9200"]'
      ELASTICSEARCH_HOSTS: '["http://34.102.87.141:9200"]'
      XPACK_SECURITY_ENABLED: false
