services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - 5602:5601
    environment:
      # ELASTICSEARCH_HOSTS: '["http://localhost:9200","http://elastic:changeme@localhost:9200", "http://34.102.87.141:9200", "http://10.0.100.140:9200"]'
      # ELASTICSEARCH_HOSTS: '["http://10.0.100.140:9200"]'
      # ELASTICSEARCH_HOSTS: '["http://34.102.87.141:9200"]'
      ELASTICSEARCH_HOSTS: '["http://elastic:changeme@localhost:9200"]'
      XPACK_SECURITY_ENABLED: false
