version: "3"
services:
  sonarqube:
    image: sonarqube:latest
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - $HOME/sonarqube_data/data:/opt/sonarqube/data
      - $HOME/sonarqube_data/extensions:/opt/sonarqube/extensions
      - $HOME/sonarqube_data/logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:16
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - $HOME/sonarqube_data/postgres:/var/lib/postgresql
      - $HOME/sonarqube_data/postgres/data:/var/lib/postgresql/data


# admin/admin-> admin/pass
