version: '3'

services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - 2181:2181

  zoonavigator:
    image: elkozmon/zoonavigator
    container_name: zoonavigator
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zookeeper:2181
      - CONNECTION_LOCALZK_CONN=localhost:2181