version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
      - "9300:9300"
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.security.autoconfiguration.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:latest
    container_name: kibana
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.encryptionKey=280f94a6-d3d0-4211-8349-918100d39105
      - xpack.security.enrollment.enabled=false
    # xpack.security.authc: 
    #   providers:
    #   basic.basic1: 
    #       order: 0 

    networks:
      - elk
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
  #   container_name: logstash
  #   volumes:
  #     - logstash_data:/usr/share/logstash/pipeline
  #   ports:
  #     - "5000:5000"
  #     - "5000:5000/udp"
  #   environment:
  #     - ELASTICSEARCH_HOST=elasticsearch
  #     - ELASTICSEARCH_PORT=9200
  #   networks:
  #     - elk
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  # logstash_data:
  #   driver: local

networks:
  elk:
    driver: bridge


# Note: Generate kibana enroll key
# 